# -*- coding: utf-8 -*-
"""AES_Code.ipynb

Automatically generated by Colaboratory.


AES ENCRYPTION & DECRYPTION

**Top Class Cryptography Project**
"""

pip install pycrypto

import hashlib
import math
import os

from Crypto.Cipher import AES

IV_SIZE = 16 # but in real 128
KEY_SIZE = 32 # 256
SALT_SIZE = 16



"""WAIT!

Project is elobrated and longer with detailed explanation.
If you want this Project.


For Project Code, PPT and Report.

Mail me at **vatshayan007@gmail.com** Now
"""

